
# 3____________________________________________
version: '3.8'
services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./results.sqlite3:/app/results.sqlite3
    ports:
      - 8000:8000
    depends_on:
      - redis
      - resend_webhook_clickhouse
  worker:
    build: .
    command: celery -A celery_worker.app worker --loglevel=info
    volumes:
      - ./results.sqlite3:/app/results.sqlite3
    depends_on:
      - redis
      - resend_webhook_clickhouse
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
  resend_webhook_clickhouse:
    image: yandex/clickhouse-server:latest
    volumes:
      - clickhouse-data:/var/lib/clickhouse
volumes:
  redis-data:
  clickhouse-data:


